### DISCUSSION TITLE
Reverse Proxy (subdir) Setup

### DISCUSSION THREAD

**Discussion by lmaddox** [healthchecks/healthchecks#1066] [Q&A]
When I go to https://InnovAnon-Inc.chickenkiller.com/healthchecks/, it redirects to https://innovanon-inc.chickenkiller.com/accounts/login/, which causes a 404. There is no rewrite rule.

nginx.conf:

```
server {
  listen 443 ssl;
  server_name InnovAnon-Inc.chickenkiller.com;
  ssl_certificate  ...
  location /healthchecks {
    proxy_pass http:/192...:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_http_version 1.1;
  }
}
```

docker-compose.yaml:

```
  healthchecks:
    environment:
      - SITE_ROOT=https://InnovAnon-Inc.chickenkiller.com/healthchecks/
    ports:
      - 8000:8000
```
