### DISCUSSION TITLE
No notification

### DISCUSSION THREAD

**Discussion by Chucky2401** [healthchecks/healthchecks#1083] [Q&A] [answered]
Hi,
I self host Healthchecks with Docker, and I don't receive any notifications anymore, it works at the beginning.

Actually, I've set up with email and MS Teams to double check. If I press the Test button, it works. But, I don't receive automatic notification, even if email is enable for up or down.

I tried to delete and recreate integrations, but nothing.

Here my config files

compose.yml

```yaml
services:
  db:
    image: postgres:16
    container_name: healtchecks-db
    volumes:
      - /mnt/docker/healthchecks/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks:
      healthchecks:
        ipv4_address: 192.168.15.10
  
  web:
    image: healthchecks/healthchecks:v3.7
    container_name: healthchecks-web
    env_file:
        - .env
    depends_on:
        - db
    networks:
      healthchecks:
        ipv4_address: 192.168.15.20
      nginx-net:
        ipv4_address: 192.168.250.25

    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'

networks:
  healthchecks:
    name: healthchecks-net
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/24
          gateway: 192.168.15.1
  nginx-net:
    external: true
```

.env

```env
ALLOWED_HOSTS=health.domain.local
APPRISE_ENABLED=True
DB=postgres
DB_CONN_MAX_AGE=0
DB_HOST=db
DB_NAME=hc
DB_PASSWORD=xxxxxxxxxxxxxxxxxxxxxx
DB_PORT=5432
DB_SSLMODE=prefer
DB_TARGET_SESSION_ATTRS=read-write
DB_USER=postgres
DEBUG=False
DEFAULT_FROM_EMAIL=noreply@domain.fr
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
EMAIL_HOST=10.166.1.102
EMAIL_HOST_PASSWORD=
EMAIL_HOST_USER=
EMAIL_PORT=25
EMAIL_USE_TLS=False
EMAIL_USE_VERIFICATION=False
INTEGRATIONS_ALLOW_PRIVATE_IPS=True
LINENOTIFY_CLIENT_ID=
LINENOTIFY_CLIENT_SECRET=
MASTER_BADGE_LABEL=Mychecks
MATRIX_ACCESS_TOKEN=
MATRIX_HOMESERVER=
MATRIX_USER_ID=
MATTERMOST_ENABLED=False
MSTEAMS_ENABLED=True
OPSGENIE_ENABLED=False
PAGERTREE_ENABLED=False
PD_APP_ID=
PD_ENABLED=False
PING_BODY_LIMIT=10000
PING_EMAIL_DOMAIN=localhost
PING_ENDPOINT=https://health.domain.local/ping/
PROMETHEUS_ENABLED=False
PUSHBULLET_CLIENT_ID=
PUSHBULLET_CLIENT_SECRET=
PUSHOVER_API_TOKEN=
PUSHOVER_EMERGENCY_EXPIRATION=86400
PUSHOVER_EMERGENCY_RETRY_DELAY=300
PUSHOVER_SUBSCRIPTION_URL=
REGISTRATION_OPEN=True
REMOTE_USER_HEADER=
ROCKETCHAT_ENABLED=False
RP_ID=
S3_ACCESS_KEY=
S3_BUCKET=
S3_ENDPOINT=
S3_REGION=
S3_SECRET_KEY=
S3_TIMEOUT=60
S3_SECURE=True
SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxx
SHELL_ENABLED=False
SIGNAL_CLI_SOCKET=
SITE_LOGO_URL=
SITE_NAME=Domain-Checks
SITE_ROOT=https://health.domain.local
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=
SLACK_ENABLED=False
# SMTPD_PORT=
SPIKE_ENABLED=False
TELEGRAM_BOT_NAME=ExampleBot
TELEGRAM_TOKEN=
TRELLO_APP_KEY=
TWILIO_ACCOUNT=
TWILIO_AUTH=
TWILIO_FROM=
TWILIO_USE_WHATSAPP=False
USE_PAYMENTS=False
VICTOROPS_ENABLED=False
WEBHOOKS_ENABLED=True
WHATSAPP_DOWN_CONTENT_SID=
WHATSAPP_UP_CONTENT_SID=
ZULIP_ENABLED=False
UWSGI_DISABLE_LOGGING=1
UWSGI_PROCESSES=2
```
