### DISCUSSION TITLE
Predictable/provisionable ping URLs and Prometheus metrics endpoints?

### DISCUSSION THREAD

**Discussion by ajgon** [healthchecks/healthchecks#700] [Q&A]
I'm deploying and maintaing all my infrastructure as a code by heavy-lifting helm and ansible files. Would it be possible, to somehow pre-configure ping and api keys for users? Either by some script, seed, migration or env variables?

Basically what I want to do, is to somehow provision automatically healtchecks.io backend and various cronjobs with ping urls from scratch, without any necessary user action - is it possible?

**Comment by cuu508** [comment]
How do you automate user creation?

If you use `manage.py createsuperuser` perhaps we could extend it to, as an option, create ping and API keys for the superuser.

**Reply by ajgon** [reply]
I think maybe the easiest solution, will be passing ping key and api keys for the super-user? So I can configure them in my scripts, pass them and reference them. Also it will be awesome, If i could do this via ENV, so something like:

```yaml
secret:
  healthchecks:
    admin_pass: pass
    ping_key: abc
    api_key: def
    api_key_readonly: ghi
```

Then, I could mount this secret under `/secrets` and create superuser:

```yaml
# container configuration
env:
  # create superuser if username and password are set
  SUPERUSER_USERNAME: admin
  SUPERUSER_EMAIL: admin@example.com
  SUPERUSER_PASSWORD_FILE: /secrets/admin_pass
  SUPERUSER_PING_KEY_FILE: /secrets/ping_key
  SUPERUSER_API_KEY_FILE: /secrets/api_key
  SUPERUSER_API_KEY_READONLY_FILE: /secrets/api_key_readonly

# under the hood
# python manage.py createsuperuser --username ${SUPERUSER_USERNAME} --email ${SUPERUSER_EMAIL}} --password-file ${SUPERUSER_PASSWORD_FILE} --ping-key-file ${SUPERUSER_PING_KEY_FILE} --api-key-file ${SUPERUSER_PING_KEY_FILE} --api-key-readonly-file ${SUPERUSER_API_KEY_READONLY_FILE}
# I suggest using files, so passwords and keys are not leaking into the logs or `docker inspect`
```

and later in my cronjobs definitions:

```yaml
command: curl https://healthchecks.ui/ping/{{ secret.healthchecks.ping_key }}/my-alert-slug
```

Does it make sense?
