### DISCUSSION TITLE
Self-hosted Healthchecks in parallel with other services behind Caddy on Oracle Cloud Infrastructure?

### DISCUSSION THREAD

**Discussion by pro-sumer** [healthchecks/healthchecks#865] [Q&A]
Currently I'm running a Mastodon instance on the [free tier](https://www.oracle.com/cloud/free/) of Oracle Cloud Infrastructure, using the [setup](https://github.com/faevourite/mastodon-oracle-cloud-free-tier) from @faevourite. The Compute VM is mostly idle, so I was hoping I could follow [your walkthrough](https://blog.healthchecks.io/2023/05/walk-through-set-up-self-hosted-healthchecks-instance-on-a-vps/) to run Healthchecks on OCI as well. Since that Mastodon setup is already using Docker and Caddy I was hoping this should even be possible for a (partial) noob like me. Unfortunately I did not succeed, but I'm willing to learn, so I hope somebody can give me some advice on how to continue.

I'm failing pretty early in your walkthrough. This is what I have done so far:

1. Added an A record pointing `hc.prosumer.dev` to the IP address of my OCI Compute VM (using [dnscontrol](https://github.com/StackExchange/dnscontrol) and Cloudflare name servers)
2. Updated `Caddyfile`
3. Updated `docker-compose.yaml`
4. Ran all the steps from the Mastodon setup [upgrade instructions](https://github.com/faevourite/mastodon-oracle-cloud-free-tier#upgrading) (which I have used successfully to upgrade my Mastodon instance)

Addition to `Caddyfile`:
```
hc.prosumer.dev {
    import cloudflare

    reverse_proxy hc:8000
}
```

(for reference; it already contained a.o. this, which works for the Mastodon instance:)
```
(cloudflare) {
  tls {
    dns cloudflare {{ cloudflare_token }}
  }
}
```

Addition to `docker-compose.yaml`:
```
  hc:
    image: healthchecks/healthchecks:latest
    restart: unless-stopped
    environment:
      - DB_NAME=/tmp/hc.sqlite
      - ALLOWED_HOSTS=hc.prosumer.dev
      - SITE_ROOT=https://hc.prosumer.dev
    networks:
      - external_network
      - internal_network
```

However, when I try to access `hc.prosumer.dev` in a browser, Cloudflare shows error code 526 (Invalid SSL certificate).

It does not seem to matter whether I use "Proxied" or "DNS only" for the A record; both options result in error 526.

I don't know whether this is relevant but I noticed that `docker container ls` lists `3000/tcp, 4000/tcp` under the `PORTS` column for "web", "streaming", and "sidekiq", but nothing at all for "hc" (shouldn't that have `8000/tcp`?).

What am I doing wrong? What am I missing?

Advice for a novice is very welcome!
