### ISSUE TITLE
SMTP with custom CA certificate

### ISSUE THREAD

**Issue by jlssmt** [healthchecks/healthchecks#1033]
Hello,

I want to self-host healthchecks.
I get the
```python
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
```
error.
Can anyone please help me to set up healthchecks with a custom CA?
Is it possible or do I need django-ca?

My docker-compose looks like this:
```yaml
services:
  healthchecks:
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    environment:
      - DB=sqlite
      - DB_NAME=/data/hc.sqlite
      - DEBUG=True
      - DEFAULT_FROM_EMAIL=XXXXXXXXX
      - EMAIL_HOST=XXXXXXXXX
      - EMAIL_HOST_PASSWORD=XXXXXXXXX
      - EMAIL_HOST_USER=XXXXXXXXX
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=True
      - EMAIL_SSL_CERTFILE=/certificates/test.pem
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - SECRET_KEY=XXXXXXXXX
      - SITE_ROOT=http://localhost:8000
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
      - ./certificates:/certificates
    restart: unless-stopped
```

Thanks in advance
