### ISSUE TITLE
ALLOWED_HOSTS is not for hostS

### ISSUE THREAD

**Issue by TristisOris** [healthchecks/healthchecks#1138]
i done initial setup with `ALLOWED_HOSTS=1.2.3.4`, then configured domain with reverse proxy `ALLOWED_HOSTS=my.com`. and here i got bunch of errors.

can't specify `ALLOWED_HOSTS=1.2.3.4,my.com` or `ALLOWED_HOSTS=["1.2.3.4","my.com]` - frontend won't start.
with only domain allowed can't generate initial account:

```
docker-compose run web /opt/healthchecks/manage.py createsuperuser
[+] Creating 1/1
 ✔ Container healthcheck-db  Running0.0s
SystemCheckError: System check identified some issues:

ERRORS:
?: (hc.api.E002) The hostname in settings.SITE_ROOT is not found in settings.ALLOWED_HOSTS
        HINT: Add '172.29.1.203' to settings.ALLOWED_HOSTS
exit status 1
```

so need to change it to ip, generate login, then change it back to domain.

**Comment by cuu508** [comment]
Please post your `docker-compose.yml` and `.env` files (edit out sensitive values of course).

**Comment by TristisOris** [comment]
```
services:
  db:
    image: postgres:16
    container_name: healthcheck-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:z,ro
      - /etc/timezone:/etc/timezone:z,ro
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    image: healthchecks/healthchecks:latest
    container_name: healthcheck-web
    restart: unless-stopped
    env_file:
        - .env
    ports:
        - 12560:8000
        # To enable SMTP on port 2525, set SMTPD_PORT=2525 in .env
        # and uncomment the following line:
        # - "2525:2525"
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
    volumes:
      - /etc/localtime:/etc/localtime:z,ro
      - /etc/timezone:/etc/timezone:z,ro
volumes:
    db_data:
```
```
ALLOWED_HOSTS=my.domain
PING_ENDPOINT=https://my.domain/ping/
SECRET_KEY=somekey
SITE_ROOT=http://1.2.3.4:8000/
```


```
*** Operational MODE: preforking ***

running "exec:./manage.py migrate" (pre app)...

SystemCheckError: System check identified some issues:

ERRORS:

?: (hc.api.E002) The hostname in settings.SITE_ROOT is not found in settings.ALLOWED_HOSTS

	HINT: Add '172.29.1.203' to settings.ALLOWED_HOSTS

command "./manage.py migrate" exited with non-zero code: 1

Fri Mar 28 13:20:26 2025 - FATAL hook failed, destroying instance

SIGINT/SIGTERM received...killing workers...

WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x78ddc3078a60 pid: 1 (default app)
```
