### ISSUE TITLE
CSRF Error with email system

### ISSUE THREAD

**Issue by eirannejad** [healthchecks/healthchecks#239]
Hello healthcheck team,
I'm getting a error when clicking on the "Email me a link" button

```
Forbidden (403)
CSRF verification failed. Request aborted.
```

Healthcheck is running in a docker container and is mapped to port "3003" so url is "localhost:3003"

**Comment by cuu508** [comment]
Hello @eirannejad, what Dockerfile are you using?

**Comment by eirannejad** [comment]
@cuu508 [This one](https://github.com/galexrt/docker-healthchecks)

**Comment by eirannejad** [comment]
And here is my `docker-compose` file

We have two domain names. Email is `@mycompany.com` but the mailserver and internal servers are under `*.mycomp-pdx.com` e.g. `mail.mycomp-pdx.com`, `data.mycomp-pdx.com`, `apps.mycomp-pdx.com`

```yaml
version: '3'

services:
  hc:
    image: galexrt/healthchecks:latest
    restart: always
    ports:
      - "3003:8000"
      - "2525:2525"
    volumes:
      - HC_Data:/healthchecks
      - HC_SQLite:/data
    environment:
      HC_HOST: "0.0.0.0"
      HC_SECRET_KEY: "blablabla"
      HC_ALLOWED_HOSTS: '["*"]'
      HC_DEBUG: "False"
      HC_DEFAULT_FROM_EMAIL: "healthcheck@mycompany.com"
      HC_USE_PAYMENTS: "False"
      HC_REGISTRATION_OPEN: "False"
      HC_EMAIL_HOST: "mail.mycomp-pdx.com"
      HC_EMAIL_PORT: "587"
      HC_EMAIL_HOST_USER: "healthcheck"
      HC_EMAIL_HOST_PASSWORD: "healthcheck-password"
      HC_EMAIL_USE_TLS: "False"
      HC_SITE_ROOT: "http://apps.mycomp-pdx.com/hc"
      HC_SITE_NAME: "MyCompany HealthChecks"
      HC_MASTER_BADGE_LABEL: "MyCompany HealthChecks"
      HC_PING_ENDPOINT: "http://apps.mycomp-pdx.com/hc/ping"
      HC_PING_EMAIL_DOMAIN: "mycompany.com"
      HC_TWILIO_ACCOUNT: "None"
      HC_TWILIO_AUTH: "None"
      HC_TWILIO_FROM: "None"
      HC_PD_VENDOR_KEY: "None"
      HC_TRELLO_APP_KEY: "None"

volumes:
  HC_SQLite:
  HC_Data:
```

This is running in a docker container behind `nginx` that is rerouting traffic to port 3003
But even if I open the `localhost:3003` in browser on the docker server itself (directly talking to the container), I get the CSRF error.

I know I'm doing something wrong but don't know what.
