### ISSUE TITLE
custom name instead of automatically generated UUID

### ISSUE THREAD

**Issue by RasHas** [healthchecks/healthchecks#491]
Could we get a possibility to use a custom name in URL instead of randomly generated UUID?

So instead of url being something like `healthchecks.example.com/ping/543dc814-81a5-11eb-8dcd-0242ac130003`
I would like to be able to set it to something like `healthchecks.example.com/ping/name-of-my-service`

For example I would then be able to specify the URL in docker-compose like this:
```
healthcheck:
      test: ["CMD", "curl", "-f", "https://healthchecks.example.com/ping/name-of-my-service"]
      interval: 60s
      timeout: 10s
```

and would not have to first create the endpoint in healthchecks and then update the url to docker-compose.

Is this possible to achieve currently? and if not is this something that is feasible to implement?
