### ISSUE TITLE
User Account and Checks Missing

### ISSUE THREAD

**Issue by mathmaniac43** [healthchecks/healthchecks#637]
Hello,

I went to sign into my self-hosted Docker container Healthchecks v1.25.0 instance for the first time in a few weeks to work on [connecting it to my HomeAssistant instance](https://github.com/custom-components/healthchecksio/issues/28#issue-1174156285)... and my login wouldn't work, which was really weird. I went into the container to mess around, and it wouldn't let me change my account's password, but eventually it allowed me to create a new account with my username, so I think somehow my account got deleted/lost.

Any ideas how to diagnose what might have happened, or has anyone experienced anything similar before? I have periodic backups that I am going to try a few of and see if I can get things back to a prior working state, but this seems like a significant-enough issue that I want to try to understand it.

Thank you.

**Comment by mathmaniac43** [comment]
Never mind... I checked my backups, and there wasn't anything in them. I think I configured my container to use SQLite, but did the Docker voluming to back up postgreSQL, so nothing was actually captured! Going to set things back up fresh using v2.0.1, **make sure the voluming works and the database is actually backed up**, and should be good to go after that.

**Comment by mathmaniac43** [comment]
In case someone has a similar issue: in addition to volume-mapping the correct directory (`/tmp`), I did have to make sure that the permissions were correct in order to write the database into it. Got the hint for that fix [here](https://github.com/healthchecks/healthchecks/issues/623#issuecomment-1079674694).

```yaml
# https://github.com/healthchecks/healthchecks
# https://hub.docker.com/r/healthchecks/healthchecks/tags
healthchecks:
    container_name: healthchecks
    image: healthchecks/healthchecks:v2.0.1
    restart: always
    networks:
        - frontend
    depends_on:
        - traefik
    environment:
        DB_NAME: /tmp/hc.sqlite
        SITE_NAME: Healthchecks
        SITE_ROOT: https://healthchecks.lan
    expose:
        - 8000 # expose http port via Traefik
    labels:
        - traefik.enable=true
        - traefik.http.routers.router-healthchecks.rule=Host(`healthchecks`, `healthchecks.lan`)
        - traefik.http.routers.router-healthchecks.entrypoints=entrypoint-https
        - traefik.http.routers.router-healthchecks.tls=true
        - traefik.http.routers.router-healthchecks.service=service-healthchecks
        - traefik.http.services.service-healthchecks.loadbalancer.server.port=8000
    volumes:
        # Had to change owner of folder on host to ensure container could write database into it
        # sudo chown -R 999:999 volumes/healthchecks/*
        - ./volumes/healthchecks/tmp:/tmp
```
