### ISSUE TITLE
Origin checking failed error

### ISSUE THREAD

**Issue by nathanielread** [healthchecks/healthchecks#640]
Receiving this error in the logs: 

```
Forbidden (Origin checking failed - https://example.com does not match any trusted origins.)
```

Running under docker-compose, using traefik as a reverse proxy and keycloak/gatekeeper as SSO. Existing postgres instance not shown below.
Using the REMOTE_USER_HEADER functionality to login, which works.

To get around the error, I had to add this line:
```
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "*").split(",")
```

in this file:
./hc/settings.py

And then I added the following env variable to the docker compose below:
CSRF_TRUSTED_ORIGINS

Was there a better way to get around that error?

```

  healthchecks:
    container_name: healthchecks
    build:
        context: $DOCKERDIR/appdata/healthchecks
        dockerfile: $DOCKERDIR/appdata/healthchecks/docker/Dockerfile
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
    image: healthchecks:local
    restart: always
    networks:
      - t2_proxy
    environment:
      - DEFAULT_FROM_EMAIL=$FROM_EMAIL
      - EMAIL_HOST=$MAILJET_SMTP_SERVER
      - EMAIL_HOST_USER=$MAILJET_USERNAME
      - EMAIL_HOST_PASSWORD=$MAILJET_PASSWORD
      - SECRET_KEY=$HEALTHCHECKS_SECRET_KEY
      - REMOTE_USER_HEADER=HTTP_X_AUTH_EMAIL
      - REMOTE_USER_HEADER_TYPE=EMAIL
      - DB=postgres
      - DB_HOST=$POSTGRES_IP
      - DB_NAME=healthchecks
      - DB_PORT=5432
      - DB_USER=$HEALTHCHECKS_DB_USERNAME
      - DB_PASSWORD=$HEALTHCHECKS_DB_PASSWORD
      - ALLOWED_HOSTS=healthchecks,localhost,healthchecks.$DOMAINNAME,$DOMAINNAME
      - CSRF_TRUSTED_ORIGINS=https://healthchecks.$DOMAINNAME
      - SITE_ROOT=https://healthchecks.$DOMAINNAME

  gatekeeper_healthchecks:
    image: quay.io/gogatekeeper/gatekeeper:1.3.8
    restart: always
    container_name: gatekeeper_healthchecks
    command: --resources $GATEKEEPER_INTERNAL
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    entrypoint:
      - /opt/gatekeeper/gatekeeper
    environment:
      - PROXY_DISCOVERY_URL=$DISCOVERY_URL
      - PROXY_CLIENT_ID=$HEALTHCHECKS_CLIENT_ID
      - PROXY_CLIENT_SECRET=$HEALTHCHECKS_CLIENT_SECRET
      - PROXY_ENCRYPTION_KEY=$HEALTHCHECKS_ENCRYPTION_KEY
      - PROXY_LISTEN=:3000
      - PROXY_ENABLE_REFRESH_TOKEN=true
      - PROXY_UPSTREAM_URL=http://healthchecks:8000
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.healthchecks-gate.entrypoints=https"
      - "traefik.http.routers.healthchecks-gate.rule=Host(`healthchecks.$DOMAINNAME`)"
      - "traefik.http.routers.healthchecks-gate.tls=true"
      - "traefik.http.routers.healthchecks-gate.tls.certresolver=dns-cloudflare"
      ## HTTP Services
      - "traefik.http.routers.healthchecks-gate.service=healthchecks-gatesvc"
      - "traefik.http.services.healthchecks-gatesvc.loadbalancer.server.port=3000"
      ## Flame
      - flame.type=application
      - flame.name=Healthchecks
      - flame.url=https://healthchecks.$DOMAINNAME
      - flame.icon=space-station

```

Also, I added this to the uwsgi.ini to fix issues with SSO redirects:

```
buffer-size = 32768
```
