### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by stepanov1975** [healthchecks/healthchecks#713]
Tried to run it in the docker container with the default configuration. I am getting 100% CPU usage for VM with two CPUs. Is it expected?

**Comment by cuu508** [comment]
No, not expected. Can you see which process is eating the CPU?

**Comment by stepanov1975** [comment]
Not sure how. Top not working inside. I tried to add htop to the Docker file. Build was completed but I still can't use htop. (I am new to docker)

**Comment by cuu508** [comment]
Try

    docker container top <container-id> u

**Comment by stepanov1975** [comment]
Adding startup log:

```
Attaching to healthchecks-postgres, healthchecks
healthchecks-postgres | 
healthchecks-postgres | PostgreSQL Database directory appears to contain a database; Skipping initialization
healthchecks-postgres | 
healthchecks-postgres | 2022-10-12 14:05:14.694 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
healthchecks-postgres | 2022-10-12 14:05:14.695 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
healthchecks-postgres | 2022-10-12 14:05:14.695 UTC [1] LOG:  listening on IPv6 address "::", port 5432
healthchecks-postgres | 2022-10-12 14:05:14.701 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
healthchecks-postgres | 2022-10-12 14:05:14.708 UTC [26] LOG:  database system was shut down at 2022-10-12 14:05:06 UTC
healthchecks-postgres | 2022-10-12 14:05:14.715 UTC [1] LOG:  database system is ready to accept connections
healthchecks | [uWSGI] getting INI configuration from /opt/healthchecks/docker/uwsgi.ini
healthchecks | *** Starting uWSGI 2.0.20 (64bit) on [Wed Oct 12 14:05:15 2022] ***
healthchecks | compiled with version: 8.3.0 on 11 October 2022 08:38:45
healthchecks | os: Linux-5.19.14-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 5 21:52:15 UTC 2022
healthchecks | nodename: 0604be8b350f
healthchecks | machine: x86_64
healthchecks | clock source: unix
healthchecks | detected number of CPU cores: 2
healthchecks | current working directory: /opt/healthchecks
healthchecks | detected binary path: /usr/local/bin/uwsgi
healthchecks | !!! no internal routing support, rebuild with pcre support !!!
healthchecks | chdir() to /opt/healthchecks
healthchecks | your memory page size is 4096 bytes
healthchecks | detected max file descriptor number: 1073741816
healthchecks | lock engine: pthread robust mutexes
healthchecks | thunder lock: enabled
healthchecks | uwsgi socket 0 bound to TCP address :8000 fd 3
healthchecks | Python version: 3.10.7 (main, Oct  5 2022, 15:06:24) [GCC 8.3.0]
healthchecks | Python main interpreter initialized at 0x564849ab9d20
healthchecks | python threads support enabled
healthchecks | your server socket listen backlog is limited to 100 connections
healthchecks | your mercy for graceful operations on workers is 60 seconds
healthchecks | mapped 162224 bytes (158 KB) for 1 cores
healthchecks | *** Operational MODE: single process ***
healthchecks | running "exec:./manage.py migrate" (pre app)...
healthchecks | Operations to perform:
healthchecks |   Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
healthchecks | Running migrations:
healthchecks |   No migrations to apply.
healthchecks |   Your models in app(s): 'api' have changes that are not yet reflected in a migration, and so won't be applied.
healthchecks |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
healthchecks | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x564849ab9d20 pid: 8 (default app)
healthchecks | *** uWSGI is running in multiple interpreter mode ***
healthchecks | spawned uWSGI master process (pid: 8)
healthchecks | spawned uWSGI worker 1 (pid: 11, cores: 1)
```

**Comment by stepanov1975** [comment]
docker-compose.yml
```
version: "3"
volumes:
    db-data:

services:
  db:
    image: postgres:latest
    container_name: healthchecks-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    container_name: healthchecks
    build:
        context: ..
        dockerfile: docker/Dockerfile
    env_file:
        - .env
    ports:
        - "8000:8000"
        # Uncomment to enable SMTP on port 25 for incoming email
        # - "25:25"
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker_installs/healthchecks/db-data
```
