### ISSUE TITLE
signal-cli binary in docker image

### ISSUE THREAD

**Issue by SecT0uch** [healthchecks/healthchecks#732]
It seems the signal-cli binary in not included in the docker image.
It is needed for the Signal integration
Would it be possible to make it available ?

Edit: Submitted #733

**Comment by cuu508** [comment]
Wouldn't it be better to signal-cli in a separate container?

**Comment by SecT0uch** [comment]
That's what I initially did, sharing the signal socket between the containers.
However signal-cli needs to be available in healthchecks container to contact the socket.
Am I missing something ?

**Comment by cuu508** [comment]
Did sharing the socket between the containers not work? What problem did you hit? 
(note – I've not personally tested running healthchecks and signal-cli in separate containers, but I assumed there must be a way to make a socket from one container available to another container)

**Comment by SecT0uch** [comment]
I did manage to share the socket between the containers.

The issue is when testing my Signal integration: `Could not send a test notification. signal-cli call failed`

**Comment by cuu508** [comment]
I got it semi-working with the following docker-compose file:

```
version: "3"
volumes:
    db-data:

services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    env_file:
        - .env
    ports:
        - "8000:8000"
    volumes:
      - "/tmp/sockets:/tmp/sockets"
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
  signal-cli:
    image: registry.gitlab.com/packaging/signal-cli/signal-cli-native:latest
    command: -a +[redacted] --config /var/lib/signal-cli daemon --socket /tmp/sockets/signal-cli.socket
    ports:
      - "7583:7583"
    volumes:
      - "/tmp/signal-cli-config:/var/lib/signal-cli"
      - "/tmp/sockets:/tmp/sockets"
    tmpfs:
      - "/tmp:exec"
```

And I had this in `.env` file:

```
SIGNAL_CLI_SOCKET=/tmp/sockets/signal-cli.socket
```

But using volumes to share sockets is quite clumsy. I had permission problems with socket files – I had to chmod the socket file so the healthchecks process would be able to access it. And, after stopping and restarting containers, the signal-cli container complained about the socket file already being there – I had to manually remove it between restarts.

I'm inexperienced with docker, there may be proper ways to solve the above issues. 

As an experimental alternative I added support for connecting to a TCP socket in 73a5cb0d572d3fa8923ab28a47409a6bfc4ac7da. TCP communication between containers is simpler–no volumes, no sokcet files:

```
version: "3"
volumes:
    db-data:

services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    env_file:
        - .env
    ports:
        - "8000:8000"
    depends_on:
        - db
        - signal-cli
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
  signal-cli:
    image: registry.gitlab.com/packaging/signal-cli/signal-cli-native:latest
    command: -a +[redacted] --config /var/lib/signal-cli daemon --tcp 0.0.0.0:7583
    volumes:
      - "/tmp/signal-cli-config:/var/lib/signal-cli"
    tmpfs:
      - "/tmp:exec"
```
And I had this in `.env` file:

```
SIGNAL_CLI_SOCKET=signal-cli:7583
```
