### ISSUE TITLE
SMTPD refuses connection after 2.7 update using Docker

### ISSUE THREAD

**Issue by marcogiorgio** [healthchecks/healthchecks#800]
Hi, I have a docker-compose file that looks like this:
<details>
  <summary>docker-compose.yml</summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
  
  ```yaml
version: "3"
services:
  healthchecks:
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    user: "${PUID}:${PGID}"
    environment:
      - DB_NAME=${DB_NAME}
      - DEBUG=${DEBUG}
      - SITE_ROOT=${SITE_ROOT}
      - SITE_NAME=${SITE_NAME}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - PING_EMAIL_DOMAIN=${PING_EMAIL_DOMAIN}
      - PING_ENDPOINT=${PING_ENDPOINT}
      - REGISTRATION_OPEN=${REGISTRATION_OPEN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - APPRISE_ENABLED=${APPRISE_ENABLED}
      - SITE_LOGO_URL=${SITE_LOGO_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SMTPD_PORT=${SMTPD_PORT}
    volumes:
      - config:/config
    ports:
      - 8001:8000
      - 2525:25
    restart: always

volumes:
  config:
  ```
  
</details>

I noticed that since the 2.7 update, I cannot connect anymore to the smtpd daemon by using any interfaces but localhost. For example:

`telnet localhost 2525`: this works
`telnet SERVER_IP 2525`: this does not work anymore

If I revert the image back to `2.6.1` everything starts working as intended again. Is anyone experiencing the same problem?
Thanks

**Comment by cuu508** [comment]
I just tested the docker-compose.yml file that is in the repository:

<details>
  <summary>docker-compose.yml</summary>

````
version: "3"
volumes:
    db-data:

services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    env_file:
        - .env
    ports:
        - "8000:8000"
        # To enable SMTP on port 2525, set SMTPD_PORT=2525 in .env
        # and uncomment the following line:
        - "2525:2525"
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
````
</details>

(I uncommented the port 2525 forward, and I added `SMTPD_PORT=2525` in `.env`)

It listens on 0.0.0.0 which is "all interfaces":

```
netstat -l | grep 2525
tcp        0      0 0.0.0.0:2525            0.0.0.0:*               LISTEN     
tcp6       0      0 [::]:2525               [::]:*                  LISTEN  
```

I'm testing this on Ubuntu 22.04, Docker 23.0.1, docker-compose 1.29.2.
