### ISSUE TITLE
Broken when Reverse Proxy - CSRF_TRUSTED_ORIGINS Missing

### ISSUE THREAD

**Issue by anymuster2** [healthchecks/healthchecks#825]
Seems like Django 4.x added mandatory origin verification - https://docs.djangoproject.com/en/4.2/ref/settings/#csrf-trusted-origins 

Healthchecks broke for me with a reverse proxy with CSRF validation errors - I was unabble to register or login as a result. Adding and additional env option and adding the line `CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split(",")` to `settings.py` fixed the issue locally.

**Comment by cuu508** [comment]
- What reverse proxy are you using? 
- What request headers is the reverse proxy passing to the app?
- What request headers is the reverse proxy adding?
- What WSGI server are you using?
- What do you have in the `CSRF_TRUSTED_ORIGINS` environment variable?
- Are you using a Docker image (which image?)?

**Comment by JKJameson** [comment]
Nice work [anymuster2](https://github.com/anymuster2), I can confirm this fixed the problem for me with Nginx.

**Comment by adelton** [comment]
For the record, adding
```
proxy_set_header Host $http_host;
```
to my Nginx TLS proxy configured with
```
proxy_pass http://localhost:8000/;
```
resolved the issue even without setting `CSRF_TRUSTED_ORIGINS` -- the https://docs.djangoproject.com/en/4.2/ref/settings/#csrf-trusted-origins says
> For requests that include the Origin header, Django’s CSRF protection requires that header match the origin present in the Host header.

so I just made the proxy play by those rules.

**Comment by JKJameson** [comment]
My NGINX block already had proxy_set_header, but it was set to $host instead of $http_host. Changing it to $http_host and removing the code changes also works.

**Comment by theko2fi** [comment]
Can confirm this issue. The error message below led me to here.

![image](https://github.com/healthchecks/healthchecks/assets/72862222/a22dbb6e-eff4-4c83-8a17-7bc196b62e9c)

I'm using **HAProxy** as reverse proxy. It took me hours to get it working. So I think it could be nice to share my solution with everybody.

There's my **HAProxy** config file `haproxy.cfg`. The most important parts to focus on, are the `frontend` and `backend` sections.

```ini
global
  stats socket /var/run/api.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
  log stdout format raw local0 info

defaults
  mode http
  timeout client 10s
  timeout connect 5s
  timeout server 10s
  timeout http-request 10s
  default-server init-addr none
  log global

resolvers docker_resolver
  nameserver dns 127.0.0.11:53

frontend stats
  bind *:8404
  stats enable
  stats uri /
  stats refresh 10s

frontend myfrontend
  bind :80
  bind :443 ssl crt /usr/local/etc/haproxy/certs/
  http-request redirect scheme https code 301 unless { ssl_fc }
  use_backend %[req.hdr(Host),lower]

backend healthchecks.traefik.me
  http-request del-header Origin
  server healthchecks healthchecks:8000 check inter 10s resolvers docker_resolver
```
This is my **healthchecks** `docker-compose.yml` file:

```yaml
version: '3.9'

networks:
  healthchecks_net:
    name: healthchecks_net
    driver: bridge
  haproxy_net:
    external: true

# services
services:
  healthchecks:
    container_name: healthchecks
    image: healthchecks/healthchecks:v2.8.1
    restart: unless-stopped
    environment:
      - DEBUG=True
      - DB=postgres
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REGISTRATION_OPEN=False
      - ALLOWED_HOSTS=healthchecks.traefik.me
      - SITE_ROOT=https://healthchecks.traefik.me
    depends_on:
      - healthchecks_database
    networks:
      - haproxy_net
      - healthchecks_net
  healthchecks_database:
    container_name: healthchecks_database
    image: postgres:15.0
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - healthchecks_net
    volumes:
    - ./data:/var/lib/postgresql/data
```
In the example above, my healthchecks instance is reachable at `http(s)://healthchecks.traefik.me`. Initially, I didn't run into this issue when using HTTP only. The problem appeared after enforcing TLS and redirecting all HTTP requests to **HTTPS** with the line ` http-request redirect scheme https code 301 unless { ssl_fc }` in the **frontend** section `haproxy.cfg` file.

### What exactly fixed the problem?

It's the line `http-request del-header Origin` in the **backend** section of HAProxy config. 

### What it actually does?

It deletes the Origin header before sending the request to the healthchecks container.

### Why?

As shown in the screenshot, the reason given for the failure is my domain name not being present in the list of trusted domains. Yes, the **Origin** header value, is the domain name requested by users. So I needed to add my domain name to that list. Unfortunately, healthchecks docker container doesn't support yet setting the `CSRF_TRUSTED_ORIGINS` environment variable.

My workaround is to delete the origin header before forwarding the requests to the backend.  

## Improvement

It could be nice in next releases if @cuu508 could add support for `CSRF_TRUSTED_ORIGINS` environment variable. It could be even better if the default value matches the `SITE_ROOT` variable value.


In the end, thanks for this amazing project @cuu508. I just heard about this a couple of days ago and already like it. I also read one of your blog posts about your motivation and your journey running [healthchecks.io](https://healthchecks.io/). It's inspiring, keep it up !
